image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      go install sigs.k8s.io/controller-runtime/tools/setup-envtest@latest
      setup-envtest use 1.19.x!
      go get 
      go build
jetbrains:
  goland:
    vmoptions: "-Xmx4g"
    prebuilds:
      version: stable
    plugins:
      - com.codestream.jetbrains-codestream
      - com.vermouthx.idea